### ISSUE TITLE
I seem to be getting an error even after following the instructions...

### ISSUE THREAD

**Issue by KingSutter** [femioladeji/react-slideshow#103]
TypeError: Cannot read property 'children' of null

```
  213 |   transitionDuration,
  214 |   onChange
  215 | } = this.props;
> 216 | const existingTweens = this.tweenGroup.getAll();
      | ^  217 | if (!existingTweens.length) {
  218 |   if (!this.divsContainer.children[newIndex]) {
  219 |     newIndex = 0;
```

**Comment by KingSutter** [comment]
Changing the line to
 `if (this.tweenGroup.getAll() != null) var existingTweens = this.tweenGroup.getAll();`
Seemed to fix the problem. But I'm not sure if this will cause other problems

**Comment by femioladeji** [comment]
I'll take a look at this and get back to you

**Comment by femioladeji** [comment]
What version are you using @KingSutter I'm trying to replicate the bug here but I can't. Can you replicate the bug on [https://codesandbox.io/](https://codesandbox.io/)

P.S you can check a codebox sample [here](https://codesandbox.io/s/admiring-wave-17e0j) to confirm that your code is perfect

**Comment by femioladeji** [comment]
@KingSutter are you still having issues with this?
