### ISSUE TITLE
Could not find a declaration file for module 'react-slideshow-image'

### ISSUE THREAD

**Issue by lioaslan** [femioladeji/react-slideshow#104]
I have just installed this package, imported and saw this error

![image](https://user-images.githubusercontent.com/24852182/95676333-962fd480-0be7-11eb-9570-dd14b145af77.png)

There're some issues about this but I met this error when I was using javascript, not typescript

**Comment by femioladeji** [comment]
Hi @lioaslan are you sure you're not using typescript. If you're using `typescript` follow [this instruction](https://react-slideshow.herokuapp.com/typescript). If you're still having issues can you please try and replicate the bug on [codesandbox.io/](codesandbox.io/)
