### ISSUE TITLE
Initial Slide progresses twice on rerender (...sometimes?)

### ISSUE THREAD

**Issue by jonshipman** [femioladeji/react-slideshow#105]
See https://codesandbox.io/s/pedantic-shannon-x7oku?file=/src/App.js

It doesn't happen all the time (might be a timing discrepancy as a nature of setTimeout itself) but when the slide encounters an additional render (even when the image array is consistent) the slideshow can "skip" the 5000ms duration and progress to the second slide. I've also observed this behavior clicking the right arrow right before the slide transitions (clicking once results in two slide progressions). 

Might be related to commit af2fc04 and the easing addition as this didn't occur last time I used react-slideshow-image.

**Comment by femioladeji** [comment]
Thanks @jonshipman I'll look into this and get back to you

**Comment by femioladeji** [comment]
@jonshipman thanks for noticing this issue. The major culprit was [this statement](https://github.com/femioladeji/react-slideshow/blob/5bd3a47b4976889ec68ede787a104eec330b3aff/src/slide.js#L65) and [also this](https://github.com/femioladeji/react-slideshow/blob/5bd3a47b4976889ec68ede787a104eec330b3aff/src/slide.js#L70). They are called on mouse down while inside the slide (clicking on the arrow is also considered mouse down). Once the state changes, a re-render happens and the reference to the timeout is lost so `clearTimeout` doesn't actually work. I've raised a PR to fix this

**Comment by femioladeji** [comment]
I've released a new version `v3.3.1`
