### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by Maarondesigns** [femioladeji/react-slideshow#109]
I saw there is another issue that has been closed but was not actually resolved. 

Everything works fine in development however after running `npm run build` this error occurs when simply including the line `import { Fade } from "react-slideshow-image";` in my code, regardless if I ever actually create a `<Fade />` component or not.

Versions are: 

    "react": "^16.14.0",
    "react-slideshow-image": "^3.3.1",

![image](https://user-images.githubusercontent.com/40376601/99464382-00821600-2906-11eb-929f-2a480d307029.png)

**Comment by femioladeji** [comment]
Hi @Maarondesigns I'm trying to replicate this error but I couldn't. Can you please try and create something on [https://codesandbox.io/](https://codesandbox.io/).

**Comment by Maarondesigns** [comment]
I don't know how to simulate running production build on that site, if it is possible at all...

**Comment by femioladeji** [comment]
@Maarondesigns can you please create a small GitHub repo so that I can clone it and test it on my machine. I would really love to get to the root of this. Also,  are you using this in SSR or as a single page application

**Comment by Maarondesigns** [comment]
It if for an internal production app at the company where I work, all front-end single page app. It is being served using IIS. When I get some time I will see if I can reproduce with a basic react app because I can’t copy/publish the code as it’s proprietary. In the end I am just doing my own custom image fader because I had to get it done this week for my work. 

Thanks,
Mike

**Comment by ebrimaconta** [comment]
I have the same issue

**Comment by femioladeji** [comment]
@ebrimaconta did you use create-react-app to set up the react app or custom webpack configuration? Can you please create a small github repo that replicates this issue. I've been trying to replicate it but I've been unable to.

**Comment by ngaboindev** [comment]
I've got the same error in production mode

**Comment by femioladeji** [comment]
@ngaboindev can you create a simple GitHub repo to replicate this issue. I've been trying to replicate it for a while now but I couldn't. Did you use create-react-app and are you using hooks?
