### ISSUE TITLE
goTo method shows last image of the array when mounting

### ISSUE THREAD

**Issue by sreeshdev** [femioladeji/react-slideshow#114]
In my react application, I used the gallery. when I click on the images, that took me to that slideshow with that index images. Its working fine but when mounting it shows the last image of that array and then it shows the correct indexed image.

**Comment by femioladeji** [comment]
@sreeshdev can you please replicate this on [codepen](codepen.io)

**Comment by femioladeji** [comment]
@sreeshdev which effect (Fade, Zoom, or Slide) gave you this bug?

**Comment by sreeshdev** [comment]
slide

**Comment by femioladeji** [comment]
@sreeshdev I've tried replicating the bug [here](https://codesandbox.io/s/naughty-austin-kvwvn?file=/src/goto.js) but I couldn't. Can you please take a look at [https://codesandbox.io/s/naughty-austin-kvwvn?file=/src/goto.js](https://codesandbox.io/s/naughty-austin-kvwvn?file=/src/goto.js) and see if you can replicate it.

Thanks
