### ISSUE TITLE
Slide skips slides

### ISSUE THREAD

**Issue by jonshipman** [femioladeji/react-slideshow#115]
As in the slide will immediate progress from index 1 to index 2 without delay. It happens when the length of slides changes with another render happening before the slides load. See example below:

Reproduced: https://codesandbox.io/s/wonderful-haze-es5xn

The setTimeout of 1000 in the second useEffect causes a render before the first useEffect finishes. Looks like an issue with the timeout not refreshing with the new render (still thinking slide length is 0 for example). I have confirmed that tying autoplay to the slide length (``autoplay={slides.length > 0}``) will prevent the problem from happening.

**Comment by femioladeji** [comment]
Good catch @jonshipman 

I've seen the bug. I'll release a fix for it.

Thanks for reproducing it

**Comment by femioladeji** [comment]
I've released a new version that fixes this bug `v3.4.2`

**Comment by AliZgheib** [comment]
Hello @femioladeji, I'm facing the same issue but I'm not sure what's the cause in my case.
I've tried having autoplay set to false. but still for some reason, the slide switches from slide index 0 -> slide index 1 on its own. I have made sure that all keys are unique 

In my case, I'm building a movie, series platform where I show different categories and I'm using your slider to display a list of images.

How I'm using the slider

    const properties = { ..., autoplay: false, ... }

<Slide  {...properties} >
array1 = [ image 1 , image 2 , image 3 , image 4]
array2 = [ image 1 , image 2 , image 3 , image 4]
array3 = [ image 1 , image 2 , image 3 , image 4]
array4 = [ image 1 , image 2 , image 3 , image 4]
array5 = [ image 1 , image 2 , image 3 , image 4]
array6 = [ image 1 , image 2 , image 3 , image 4]
</Slide>

And on the main page, I'm looping through the list of categories and creating multiple slide components.
Any idea on what could be the reason behind this? Sometimes the slides are fine, sometimes in one of the slide components it keeps moving from array 1 -> array 2 even though autoplay is false.

**Comment by femioladeji** [comment]
@AliZgheib do you update the images array after the component has been mounted? And if possible can you recreate this bug on `codesandbox.io`

**Comment by AliZgheib** [comment]
Hello again @femioladeji, and thank you for the fast reply. I'll take a deeper look at when the image array gets updated and see if it's causing the issue. if not, ill try to re-create the bug.

I will keep you updated.

**Comment by AliZgheib** [comment]
Hello,

You were right about the component being mounted and changes to the data array causing this issue.
I added a check before the render method and returned null in case the array was empty (waiting API call)
and now the sliders working as expected. I tested it multiple times to make sure it's working correctly and it was all good.

Thank you alot for your time and the fast feedback too :)
