### ISSUE TITLE
Wrapping indicators inside of a ul tag.

### ISSUE THREAD

**Issue by SalahAdDin** [femioladeji/react-slideshow#118]
My client is using this package to create a wonderful slider; unfortunately, this has a problem with accessibility:
![image](https://user-images.githubusercontent.com/5034215/102013644-8e64eb80-3d62-11eb-8401-a2b248ea7f7d.png)

And it comes from:
![Screen Capture_select-area_20201213164320](https://user-images.githubusercontent.com/5034215/102013671-ba806c80-3d62-11eb-8f32-68e560f2a95c.jpg)

It is easy to solve, i think, by wrapping the indicators in a `ul` tag.

Thanks

**Comment by femioladeji** [comment]
Oh ok @SalahAdDin thanks for pointing this out. I'll look into fixing this

**Comment by femioladeji** [comment]
@SalahAdDin a new version has been released that fixes this bug v3.4.3
