### ISSUE TITLE
Glitching of the slider when used inside a css grid

### ISSUE THREAD

**Issue by AlexanderProd** [femioladeji/react-slideshow#122]
When I'm using the slider inside a css grid it glitches out of the screen and gets extremely big. 
I've noticed this when comparing my site on mobile vs on the desktop. On big screens the slider sits inside a grid while on small screens it does not. 

This is how it looks like when I load the page with the slider on a large screen (`disply: grid` applies).
https://user-images.githubusercontent.com/3080903/106955064-fd443c80-6734-11eb-8cd2-7911a2ffc407.mov

The `div` with the slider in it gets extremely big which causes the glitching and the whole layout to break.
<img width="1680" alt="Bildschirmfoto 2021-02-04 um 22 06 09" src="https://user-images.githubusercontent.com/3080903/106955270-4eecc700-6735-11eb-884e-e3e667f96984.png">

This is the styled component where the slider sits in. 

```JS
export const TwoColumnGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: ${({ gap }) => (gap ? gap : '2.5rem')};
  grid-auto-flow: row dense;
  ${({ backgroundColor }) =>
    backgroundColor ? `background-color: ${backgroundColor};` : null};

  & > :nth-of-type(4n - 1) {
    grid-column-start: 2;
  }

  @media (max-width: ${breakpoints.l}px) {
    display: block;

    & > * {
      margin-bottom: ${({ gap }) => (gap ? gap : '2.5rem')};
    }

    & > :last-child {
      margin-bottom: 0rem;
    }
  }
`
```

I've noticed I can work around by wrapping the slider inside a container with an absolute width like `width: 200px` but this defeats the purpose of the slider filling my container. 

I'm using Emotionjs@11.0.0 with Gatsby@2.32.0, React@17.0.1 and react-slideshow-image@3.4.3

**Comment by femioladeji** [comment]
@AlexanderProd thanks for this. I'll look into it and get back to you

**Comment by femioladeji** [comment]
Hi @AlexanderProd can you try using this for the `grid-template-columns`
```css
grid-template-columns: repeat(2, minmax(0, 1fr));
```
Check [this article] for more details.

Let me know if it works or not

**Comment by AlexanderProd** [comment]
@femioladeji Thank you very much! That fixed it.
