### ISSUE TITLE
Slide effect not pass react test

### ISSUE THREAD

**Issue by AREEG94FAHAD** [femioladeji/react-slideshow#129]
I am try to pass react test but this appear to me when i use slide effect

    TypeError: Cannot read property 'querySelectorAll' of null

      10 | it('renders correctly', () => {
      11 |   const tree = renderer
    > 12 |     .create(
         |      ^
      13 |       <Provider store={store}>
      14 |         <Router>
      15 |           <Home store={store} />

**Comment by femioladeji** [comment]
@AREEG94FAHAD are you saying your test is failing because of the package? Can you try and log the test-mounted HTML? Also what testing framework are you using

**Comment by AREEG94FAHAD** [comment]
I am using this test
https://www.npmjs.com/package/react-test-renderer
when I remove Slid component it work fine. 
I don't understand this 
"Can you try and log the test-mounted HTML"

**Comment by femioladeji** [comment]
@AREEG94FAHAD I've been able to replicate the bug. I'll push a fix soon. Thanks for reporting this

**Comment by femioladeji** [comment]
After a bit of digging, I discovered this is an issue with react-test-renderer not working well with refs as noted in this issue https://github.com/facebook/react/issues/7740

I'll try and look for a way to fix the bug

**Comment by AREEG94FAHAD** [comment]
Awesome I really I appreciate your effort

**Comment by femioladeji** [comment]
@AREEG94FAHAD I've released a new version that fixes the issue. Can you install `v3.4.6`
