### ISSUE TITLE
Non infinite slide effect is not working correctly

### ISSUE THREAD

**Issue by sourabkapoor** [femioladeji/react-slideshow#144]
I was trying to use a combination of infinite and canSwipe props and I noticed that when i used ` infinite={false}` and `canSwipe={true}` I am getting an abnormal effect like:
![image](https://user-images.githubusercontent.com/36324561/134629670-9bdc6396-e659-450f-b296-6dc8c6535092.png)

It is showing partial last image which is not supposed to happen with infinite = false. 

Is there any way i can keep infinite to false and still manage to have this swipe feature for my mobile devices.

**Comment by femioladeji** [comment]
@sourabkapoor I'll look into this and get back to you

**Comment by femioladeji** [comment]
There's a new release v3.5.1 with a fix for this issue
