### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by MohamedWSalah** [femioladeji/react-slideshow#149]
So, I noticed that slidesToShow isnt responsive, which means if I set it to 2, it will always show 2 slides even on mobile view.

Could overcome that by grabbing the screen width on rendering, and change the value of slidesToShow conditionally,  but would be nice if there is a way to make it fill depending on the elements width.

**Comment by femioladeji** [comment]
@MohamedWSalah thanks for raising this issue. I'll look into it and get back to you

**Comment by femioladeji** [comment]
A new version `3.7.0` has been released that has support for `responsive` settings. You can check the documentation [here](https://react-slideshow-image.netlify.app/responsive)
