### ISSUE TITLE
Transition is laggy

### ISSUE THREAD

**Issue by OliviaAdler** [femioladeji/react-slideshow#158]
hey I've been using you package, I have a problem in transition, my transition duration is 300ms and when going to next or prev slide , it is smooth in windows but laggy in macOS also in both Chrome and Firefox.

versions
npm 8.1.2
node v16.13.2,
Windows 10-11,
react-slideshow-image:  3.7.0

**Comment by femioladeji** [comment]
I'll look into this and get back to you

**Comment by cyntler** [comment]
@OliviaAdler check again in the new release.
