### ISSUE TITLE
Jumping Effect when there is a server side rendering

### ISSUE THREAD

**Issue by lureevnat** [femioladeji/react-slideshow#165]
Hii @femioladeji ,

When I am doing server sider rendering (by using nextjs), All six images are showing on the webpage first, and then becoming a carousel later which is creating jumping effect. but when I am stopping server side rendering Its working fine. But I need server side rendering.

Any Help???

**Comment by femioladeji** [comment]
Hi, yes I've noticed some issues with server side rendering and I'm already working on a fix. Hopefully by weekend a new version should be released that will fix the issues

**Comment by femioladeji** [comment]
@lureevnat what version of react are you using please?

**Comment by lureevnat** [comment]
I am using      "react-slideshow-image": "^3.4.6".  I am also added my remaining dependencies if in case of need @femioladeji 

  "dependencies": {
    "@badrap/bar-of-progress": "^0.1.2",
    "@tailwindcss/typography": "^0.4.0",
    "axios": "^0.21.1",
    "html-react-parser": "^1.2.6",
    "moment": "^2.29.1",
    "next": "^10.2.3",
    "react": "17.0.1",
    "react-device-detect": "^1.17.0",
    "react-dom": "17.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^10.2.5",
    "postcss": "^8.2.8",
    "react-alice-carousel": "^2.5.1",
    "react-slideshow-image": "^3.4.6",
    "tailwindcss": "^2.1.0",
    "webpack-preprocessor-loader": "^1.1.4"
  }

**Comment by lureevnat** [comment]
Sure @femioladeji, I will try 3.7.2 and if still there is an issue I will create a small bug and update you.

**Comment by lureevnat** [comment]
I checked it just now and I am still seeing the issue. Sorry, Forgot to tell you. The issue was coming production mode, I am not able to see that flick/jump while in dev mode. You can check that in production clearly by disabling javascript for that webpage and run. Mean while I will create a bug in codesandbox.com

**Comment by cedricdelpoux** [comment]
Hi @femioladeji, I'm also annoyed with the same issue.

Without Javascript:
<img width="916" alt="Capture d’écran 2022-04-28 à 14 47 34" src="https://user-images.githubusercontent.com/2683300/165755353-5a5abab6-36a2-4eab-8384-14e844f45f86.png">

With javascript enabled.
<img width="564" alt="Capture d’écran 2022-04-28 à 14 48 05" src="https://user-images.githubusercontent.com/2683300/165755489-e368b4ba-0c56-4aec-8fb6-097c0bb3fd02.png">

You can checkout my website homepage and disable javascript in the developper console to see the issue:
https://cedricdelpoux.fr/en

**Comment by femioladeji** [comment]
Thanks for raising this issue. It has now been fixed in the new release v3.7.5

**Comment by femioladeji** [comment]
#175
