### ISSUE TITLE
'Slide' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by nahuelDev23** [femioladeji/react-slideshow#169]
In NEXT.js  when i try make build i get the following error:

```
Type error: 'Slide' cannot be used as a JSX component.
  Its instance type 'Slide' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/home/akerman/Documentos/sandbox/teslo-shop/node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
          Type '{}' is missing the following properties from type 'ReactPortal': key, children, type, props
```
I already followed the repository instructions for typescript, which is down. That's where I got this from.

```

  declare module 'react-slideshow-image' {
    export class Zoom extends React.Component<ZoomProps & any, any> {
        goBack(): void;
        goNext(): void;
        goTo(index: number): void;
    }
    export class Fade extends React.Component<SlideshowProps & any, any> {
        goBack(): void;
        goNext(): void;
        goTo(index: number): void;
    }
    export class Slide extends React.Component<SlideshowProps & any, any> {
        goBack(): void;
        goNext(): void;
        goTo(index: number): void;
    }
    export interface SlideshowProps {
        duration?: number,
        transitionDuration?: number,
        defaultIndex?: number,
        indicators?: boolean | function,
        prevArrow?: object | function,
        nextArrow?: object | function,
        arrows?: boolean,
        autoplay?: boolean,
        infinite?: boolean,
        onChange?(oldIndex: number, newIndex: number): void,
        pauseOnHover?: boolean,
        slidesToShow?: number,
        slidesToScroll?: number,
        canSwipe?: boolean,
        easing?: string,
        cssClass?: string
    }
    export interface ZoomProps extends SlideshowProps {
        scale: number
    }
  }

```
in types/react-slideshow-image/index.d.ts but not work... thx

**Comment by femioladeji** [comment]
@nahuelDev23 thanks for raising this issue. I'll look into this and get back to you. I'll look into it and hopefully get back to you by tomorrow

**Comment by maurciobuffa** [comment]
Hi!
I'm facing the same problem. Were you able to find any solution?

Thanks

**Comment by femioladeji** [comment]
Hi all, sorry for the delay in fixing this. I had to switch laptops recently and I'm still in the setup phase. I'll look into it this weekend

**Comment by maurciobuffa** [comment]
I was able to fix this problem through this solution:

https://stackoverflow.com/questions/71791347/npm-package-cannot-be-used-as-a-jsx-component-type-errors/71828113#71828113

**Comment by femioladeji** [comment]
I've tried replicating this issue but I couldn't. Can I see what your package.json looks like? Also did you check [this out](https://stackoverflow.com/questions/71791347/npm-package-cannot-be-used-as-a-jsx-component-type-errors/71828113#71828113) perhaps the solution there may also resolve the problem

**Comment by maurciobuffa** [comment]
I had the same problem with another package too and the solution you just shared in that post fixed the problem

Thanks for your time @femioladeji
