### ISSUE TITLE
Custom indicators className problem

### ISSUE THREAD

**Issue by mattponiat** [femioladeji/react-slideshow#172]
Hello!
While making custom indicators I had to add `className="each-slideshow-indicator"` for the `active` pseudo-class to work correctly.
In the docs [here](https://react-slideshow-image.netlify.app/custom-indicators) it shows you need to add `className="indicator"`, but that didn't work for me.

I'm using NextJS ver.12.1.5 and react-slideshow-image ver.3.7.3

**Comment by femioladeji** [comment]
@mattponiat the `active` class is added to the current indicator. If you check [this](https://codesandbox.io/s/serene-lalande-yjmol?file=/src/App.js) out you'll notice that the active class is appended to the indicator that is currently in view.


P.S you can use any class name you want. You can check [this out](https://codesandbox.io/s/dawn-meadow-ki2s68?file=/src/App.js)
![Screenshot 2022-05-07 at 18 43 31](https://user-images.githubusercontent.com/17332992/167263772-56d61298-8d5a-4bd4-8a0e-2876dec13aa6.png)

**Comment by mattponiat** [comment]
@femioladeji Thank you for the reply. I can see that it works, but for some reason using any class name wouldn't work for me. It would only work if I added the default `className="each-slideshow-indicator"`. I can see in my app that `active` class name is being added but the styles don't apply.
It's not really an issue, I just thought it's worth mentioning if there is any bug happening.

**Comment by femioladeji** [comment]
@mattponiat can you double check your css. Maybe there's a conflict or a style is being overwritten. The only thing the package does is to add the `active` class. The actual styling is left to the consumer of the package

**Comment by mattponiat** [comment]
I honestly don't know, I checked everything. I also want to mention that I'm using styled-components, so maybe that's conflicting, but I'm making the indicators the same way you showed me in your examples. I think we can close this issue.
