### ISSUE TITLE
the css is not working properly

### ISSUE THREAD

**Issue by Abdexgerji** [femioladeji/react-slideshow#177]
the slideshow image have a very small height and donot show properly

**Comment by spidgorny** [comment]
![image](https://user-images.githubusercontent.com/1579235/182873486-4d055763-cc30-4e38-996a-639c9468391c.png)

Very narrow (height of the icons). The parent div should have some `height: 100%` or something similar? I'm using bootstrap.css. Does it interfere?

**Comment by femioladeji** [comment]
@spidgorny thanks for reporting this bug. I'm guessing you're using background image. Can you follow this codesandbox [https://codesandbox.io/s/priceless-banach-sugm14?file=/src/slideshow.jsx](https://codesandbox.io/s/priceless-banach-sugm14?file=/src/slideshow.jsx]
