### ISSUE TITLE
module not found error in Next.js

### ISSUE THREAD

**Issue by TalDahan22** [femioladeji/react-slideshow#181]
I'm trying to use the Slide for my Next.js project.
It's not working and shows me this error:

![image](https://user-images.githubusercontent.com/106315475/176687825-40c606f9-988d-44a4-93e6-5109ecb0514a.png)

**Comment by femioladeji** [comment]
Hi @TalDahan22 sorry about this. We are currently working on releasing a new version with full support for typescript. The new version should be released this weekend. I'll inform you once that's done

**Comment by femioladeji** [comment]
hi @TalDahan22 a new version 4.0.0 has now been released. That will solve this bug. Sorry about that
