### ISSUE TITLE
Skip transition option

### ISSUE THREAD

**Issue by suciueus** [femioladeji/react-slideshow#198]
It would be great to have an option to skip the transition (animation) on `goTo` action. 

If you have a dozen slides and you open the last one first it would transition through all of them. I know we have a `defaultIndex` option but we can't change that once the slideshow is initialized.

I came across this because I open the slideshow in a modal window and use it to swipe through the images.

**Comment by femioladeji** [comment]
@suciueus good point. I'll look into this and get back to you

**Comment by femioladeji** [comment]
@suciueus a new version has been released. Now you can pass a second parameter to the `goTo` method like this
```ts
slidref.current.goTo(2, { skipTransition: true });
```

**Comment by suciueus** [comment]
awesome! this covers more usecases now. thanks for the swift response on this
