### ISSUE TITLE
How to make a vertical slide show?

### ISSUE THREAD

**Issue by vvviettt** [femioladeji/react-slideshow#214]
I need make a slide show look like this
![Screenshot 2023-06-22 at 08 21 35](https://github.com/femioladeji/react-slideshow/assets/97574971/1236e0e6-3ade-4967-8694-ece69df6a259)
I don't find solution for this in your document.
Thank you so murch!

**Comment by femioladeji** [comment]
@vvviettt we currently don't have this functionality but we'll look into implementing it and get back to you

**Comment by femioladeji** [comment]
Support for vertical slideshow has now been released in the latest version. You just have to pass the `vertical` prop to the `slide` component. https://react-slideshow-image.netlify.app/?path=/story/examples-vertical--page
