### ISSUE TITLE
Use state for defaultIndex

### ISSUE THREAD

**Issue by danoshi** [femioladeji/react-slideshow#219]
Hi I have currently the issue that I can't set the myactiveImageState to the defaultIndex property. 
Here is an example of what I am doing

https://codesandbox.io/s/fervent-margulis-jstpgj?file=/src/App.tsx

As you can see in the last diff I have this onClick method and if one of the "small" images is clicked I would like to update my silder as well but for now giving the defaultIndex the value slideActiveImageIndex is not working as the main picture is not chaning and I get this typescirpt error below 

Type '{ children: Element[]; defaultIndex: { slideActiveImageIndex: number; }; transitionDuration: number; canSwipe: boolean; autoplay: boolean; }' is not assignable to type 'Pick<SlideProps, "responsive" | "slidesToShow" | "slidesToScroll" | "children" | "duration" | "transitionDuration" | "defaultIndex" | "indicators" | "prevArrow" | ... 9 more ... | "onChange">'.
  Types of property 'defaultIndex' are incompatible.
    Type '{ slideActiveImageIndex: number; }' is not assignable to type 'number'.ts(2322)
    
    
    
I don't know if my approach is supported or not or if I am doing something wrong here so I really appriciate any help!

**Comment by danoshi** [comment]
The behavior I want to achieve is as follows: when I press on the slider left or right, my thumbnail pictures below will get a border indicating the current index of the slider. The second thing I want to achieve is this: when the slider is, for example, on index 1, and a user clicks on a thumbnail picture with index 3, the picture in the slider will change to the picture at index 3.

I tried to accomplish this using the defaultIndex and onChange properties in the slider, but I didn't have any success. I hope someone can help me make progress with this.

**Comment by femioladeji** [comment]
@danoshi I'll investigate this and get back to you but I think what you need to do is use the `goTo` method. I'll try to create an example codesandbox app and share with you

**Comment by danoshi** [comment]
Thank you very much for the response, an example would definitely help me out! Will wait for feedback from you

**Comment by femioladeji** [comment]
@danoshi is this what you're trying to achieve
https://codesandbox.io/s/smoosh-shape-qwdy4t?file=/src/carousel.tsx

**Comment by femioladeji** [comment]
@danoshi can you please let me know if the sandbox shared earlier worked for your use case

**Comment by danoshi** [comment]
Hi @femioladeji the sandbox example is exactly what I need, thank you very much!! I will have a look on my code and do the adjustments with your example. Again I really appreciate your help and thanks 👍

**Comment by femioladeji** [comment]
cool, glad I could help
