### ISSUE TITLE
Responsive only occurs when window changes

### ISSUE THREAD

**Issue by mbalex99** [femioladeji/react-slideshow#24]
So I have the component in a bootstrap

```jsx
<div className="col-md-6">
```

But for some reason it's only responsive if I move the window. Not sure what I should do?

Here's a video of what's happening. 
https://www.youtube.com/watch?v=fMLYJOAmn7k

**Comment by andela-foladeji** [comment]
I'll look into this and get back to you

**Comment by andela-foladeji** [comment]
Can you share what your `jsx` looks like. I'm having issues replicating the bug here

**Comment by andela-foladeji** [comment]
@mbalex99 I just cloned this repo https://github.com/mbalex99/react-slides-bug-demo installed all the necessary dependencies and it worked fine on my browser. I use a chrome v70. Something must be wrong somewhere. I'm curious to find out what's happening.

**Comment by mbalex99** [comment]
Ah I see this thing is only happening with hot module reloading....

*Maximilian Alexander*
www.ditto.live ( http://www.ditto.live )
San Francisco, CA 

Sent via Superhuman iOS ( https://sprh.mn/?vip=mbalex99@gmail.com )
