### ISSUE TITLE
Images list change not refreshing

### ISSUE THREAD

**Issue by miliu99** [femioladeji/react-slideshow#29]
Thanks very much for sharing this. It works except, as the title says, it doesn't refresh when you give a new list of images. It looks like you forgot to implement componentWillReceiveProps? I don't see it in Slideshow class in slide.js. Should be an easy fix, right?

**Comment by femioladeji** [comment]
Oh yeah, I didn't add it. I will make that adjustment soon. Thanks for pointing it out @miliu99

**Comment by femioladeji** [comment]
#30 This issue has been fixed in the attached PR. Thanks @miliu99

**Comment by miliu99** [comment]
Thank you very much trying to fix it. I just tried and the problem does seem to be fix because I can see the new images as they are added. However, I got a ton of error in chrome console log like this:

Uncaught TypeError: Cannot read property 'style' of undefined
    at ./node_modules/@tweenjs/tween.js/src/Tween.js.TWEEN.Tween._onUpdateCallback (fade.js:240)
    at ./node_modules/@tweenjs/tween.js/src/Tween.js.TWEEN.Tween.update (Tween.js:390)
    at _Group.update (Tween.js:66)
    at animate (fade.js:234)

Can you please look into it?

**Comment by femioladeji** [comment]
@miliu99 please when does the error occur, I'm having a hard time replicating it here

**Comment by femioladeji** [comment]
I just made a new deployment now, please let me know if it fixed the bug or tell me steps to reproduce it. Thanks

**Comment by miliu99** [comment]
Thank you very much for quick response. I just tried with 1.1.5 and got the
same error as

[image: image.png]

Here is my code.

<div className={className} style={style}>
{images.length <= 1 ? <div className="each-slide">
<img src={images[0].imageUrl} alt="" className={slideClass || 'slide'}/>
</div> :
<Fade {...properties}>
{images.map((x, i) => <div key={i} className="each-slide">
<div className={slideClass || 'slide'} style={{ backgroundImage: `url(${x.
imageUrl})`, backgroundSize: 'cover', backgroundPosition: 'center'}}></div>
</div>)}
</Fade>}
</div>

To work around the initial problem, in my case, as I always start with a
single image, I first just show the image, and when I get more images, I
switch to your slideshow Fade. This code is still working fine.

Now, if I want to use your component completely, I can just change the
image.length <= 1 to image.length <= 0. Then, I got all the errors shown
above.

**Comment by miliu99** [comment]
oh, I forgot to mention...this is the properties passed in

const properties = {
duration: 10000,
transitionDuration: 2000,
infinite: true,
indicators: false,
arrows: false
}

**Comment by miliu99** [comment]
Also,  I start with one image and there is no error. The error happens when
I feed more images. So, it appears it has something to do with
componentWillReceiveProps.

**Comment by miliu99** [comment]
Ok, I just debugged through your code. The error occurs at line 240 of
fade.js

      var tween = new TWEEN.Tween(value).to({ opacity: 1 },
transitionDuration).onUpdate(function (value) {
        _this4.divsContainer.children[newIndex].style.opacity =
value.opacity;

**Comment by miliu99** [comment]
This if-check seems to fix that problem:

      var tween = new TWEEN.Tween(value).to({ opacity: 1 },
transitionDuration).onUpdate(function (value) {
        if (_this4.divsContainer.children[newIndex])
_this4.divsContainer.children[newIndex].style.opacity = value.opacity;
        if (_this4.divsContainer.children[index])
_this4.divsContainer.children[index].style.opacity = 1 - value.opacity;
      }).start();

**Comment by femioladeji** [comment]
@miliu99 please can you completely uninstall the package and reinstall it. The fact that it's still complaining about line 240 shows the new updates wasn't there. Thanks for helping me debug 😄 let me know how to re-installing goes

**Comment by miliu99** [comment]
You are right. It does work after I uninstall and reinstall. Thank you very
much!

By the way, thank you for sharing this package. May I suggest an
improvement? For me, I'd like to be able to mix multiple effects in a
slideshow randomly, like, fading, sliding and so on. Is it possible?

**Comment by femioladeji** [comment]
@miliu99 that's not possible for now. I'll think about it later. Thanks for the suggestion
