### ISSUE TITLE
All items stacking instead of displaying on top of each other

### ISSUE THREAD

**Issue by fortydegrees** [femioladeji/react-slideshow#42]
Hi, this looks like a great lightweight library, so thanks for developing it.

I'm using NextJS with the Grommet v2 component library, and when I try and implement the carousel, all the items are stacked, occupying lots of vertical space (flex-direction for the container they're in is vertical).

They still fade out and in sequentially, but the behaviour should be that they fade out and in at the same location, on top of each other.

My initial thought was to fix it with `position: absolute`, and this did fix it, but creates the much greater monster of having to absolutely position the slideshow. I've also tried changing all the <Box> tags to <divs>, similar to the example page, with no luck.

```
import { Box, Heading, Text, Button, Stack } from 'grommet'
import Link from 'next/link'
import { Fade } from 'react-slideshow-image'

const fadeProperties = {
  duration: 4000,
  transitionDuration: 500,
  infinite: true,
  indicators: true,
  onChange: (oldIndex, newIndex) => {
    console.log(`fade transition from ${oldIndex} to ${newIndex}`)
  }
}

const LastGame = props => {
  return (
    <Box background='white' elevation='small' round='xsmall' fill='vertical'>
      <Box
        background='light-1'
        pad='small'
        fill='horizontal'
        border={{
          size: 'xsmall',
          style: 'solid',
          side: 'bottom',
          color: 'light-6'
        }}
      >
        <Text weight='bold'>Your Most Recent  Game</Text>
      </Box>
      <Box background='white' pad='small' align='center'>
        <Heading level='3' margin='none'>
          {props.closed[4].game.title}
        </Heading>
        <Box>
          <Fade {...fadeProperties}>
            {Object.keys(props.closed[4].game.questions).map((key, idx) => {
              return (
                <Box
                  flex
                  key={key}
                  border={{
                    color: 'dark-1',
                    size: 'medium',
                    style: 'solid',
                    side: 'all'
                  }}
                  elevation='medium'
                  height='18rem'
                  round='small'
                  margin='medium'
                >
                  <Stack fill>
                    <Box fill>
                      <video
                        style={{ objectFit: 'cover' }}
                        height='100%'
                        src={
                          `https://cdn.playballpark.com/` +
                          props.closed[4].game.questions[key].img
                        }
                        autoPlay
                        loop
                        muted
                        playsInline
                      />
                    </Box>
                    <Box fill>
                      <Box justify='around' flex='grow' align='center'>
                        <Box
                          background='dark-1'
                          pad={{ horizontal: 'medium', vertical: 'xsmall' }}
                          round='xsmall'
                        >
                          <Text weight='bold' color='light-1'>
                            {props.closed[4].game.questions[key].question}
                          </Text>
                        </Box>
                        <Box
                          background='dark-1'
                          pad={{ horizontal: 'medium', vertical: 'xsmall' }}
                          round='xsmall'
                        >
                          <Text weight='bold' color='light-1'>
                            {props.closed[4].prediction[key]}
                          </Text>
                        </Box>
                      </Box>
                    </Box>
                  </Stack>
                </Box>
              )
            })}
          </Fade>
        </Box>
      </Box>
    </Box>
  )
}

export default LastGame

```

I know this probably isn't really a bug with the library, but I'm not quite sure how to solve this myself and was hoping someone here could give me some insight into what I'm missing, and what properties I need to apply & where..

**Comment by fortydegrees** [comment]
It seems like it's a similar problem to this closed issue: https://github.com/femioladeji/react-slideshow/issues/9 - is pulling external files the problem?

**Comment by femioladeji** [comment]
@fortydegrees I'll try and replicate the bug and get back to you

**Comment by femioladeji** [comment]
@fortydegrees you can load images remotely. I think this is most likely caused by an issue with your styles. You can start by keeping the content in the <fade> simple and then grow from there

**Comment by fortydegrees** [comment]
Hi @femioladeji , thanks very much for the quick response. I don't disagree that it's an issue with my styles, but I've just stripped away everything and still encounter the same issue. Here is the current code I'm testing it with.

```
import { Fade } from 'react-slideshow-image'

const fadeImages = [
  'https://cdn.playballpark.com/102SHccqRCzzhK.mp4',
  'https://cdn.playballpark.com/37q0fnUan3nTtuASIo.mp4'
]

const fadeProperties = {
  duration: 4000,
  transitionDuration: 500,
  infinite: true,
  indicators: true,
  onChange: (oldIndex, newIndex) => {
    console.log(`fade transition from ${oldIndex} to ${newIndex}`)
  }
}

const Carousel = props => {
  return (
    <div className='slide-container'>
      <Fade {...fadeProperties}>
        <div className='each-fade'>
          <div className='image-container'>
            <video
              src={fadeImages[0]}
              autoPlay
              loop
              muted
            />
          </div>
          <h2>First Slide</h2>
        </div>
        <div className='each-fade'>
          <div className='image-container'>
            <video
              src={fadeImages[1]}
              autoPlay
              loop
              muted
            />
          </div>
          <h2>Second Slide</h2>
        </div>
      </Fade>
      <style jsx>{`
        slide-container {
          width: 70%;
          margin: auto;
        }

        h3 {
          text-align: center;
        }

        .each-slide > div {
          display: flex;
          align-items: center;
          justify-content: center;
          background-size: cover;
          height: 300px;
        }

        .each-slide span {
          padding: 20px;
          font-size: 20px;
          background: #efefef;
          text-align: center;
        }

        .each-fade {
          display: flex;
        }

        .each-fade .image-container {
          width: 75%;
          overflow: hidden;
        }

        .each-fade .image-container img {
          width: 100%;
        }

        .each-fade h2 {
          width: 25%;
          display: flex;
          justify-content: center;
          align-items: center;
          margin: 0;
          background: #adceed;
        }
      `}</style>
    </div>
  )
}
export default Carousel
```


Does anyone have experience with getting this to work with NextJS? I really can't work out what the issue could be...

**Comment by femioladeji** [comment]
This is what I have when I copied your code https://drive.google.com/file/d/18glZvm1EV2PfaCbJiNqOwPH96KHFxGts/view?usp=sharing.

If it's specifically an issue with nextjs check the readme, there's a section there for next.js configuration. I hope it helps

**Comment by fortydegrees** [comment]
Hi, I followed the section for NextJS as the code doesn't compile without it. I have recreated the error in a codesandbox here:

https://codesandbox.io/s/hello-world-bwh06

This issue only occurs when _app.js and _document.js are present, but I still can't really work out what's causing it. Once again I understand this isn't really an issue with your library, but I can't wrap my head around what the bug could be, and feel like you might be in a better position to diagnose it.

**Comment by fortydegrees** [comment]
Just as an update, even without _app.js and _document.js the issue persists. 

I've recreated the most bare-bones NextJS project, with just this component, to demonstrate the issue: https://codesandbox.io/s/hello-world-j9r5k

**Comment by femioladeji** [comment]
@fortydegrees change the next.config.js to this

const withCSS = require("@zeit/next-css");

if (typeof require !== "undefined") {
  require.extensions[".css"] = file => {};
}

module.exports = {
  webpack: config => {
    // Fixes npm packages that depend on `fs` module
    config.node = {
      fs: "empty"
    };

    return config;
  }
};

module.exports = withCSS({
  cssModules: false,
  cssLoaderOptions: {
    url: true
  }
});

the `cssModules` option should be false

**Comment by femioladeji** [comment]
@fortydegrees you can check this out https://codesandbox.io/s/slideshow-for-next-wj3gf

**Comment by fortydegrees** [comment]
Amazing! It works! Thanks so much!

I feel like this could be quite a common issue with larger NextJS projects - I don't think I'd have ever worked it out. Thanks for the help and the great module

**Comment by femioladeji** [comment]
There are several issues on the @zeit/next-css github repository related to how the package handles css in 3rd party packages. If you have more problems with this you can re-open this issue
