### ISSUE TITLE
Support for SSR?

### ISSUE THREAD

**Issue by fortydegrees** [femioladeji/react-slideshow#43]
Is this planned in the future?

**Comment by femioladeji** [comment]
There's actually support for NextJs, you'll need to make some edits in the next.config.js file. Are you having issues using it @fortydegrees. Let me see the error you're having

**Comment by fortydegrees** [comment]
I think it has to do with SSR. I have it working on NextJS fine thanks to the great instructions in the module document.

However when I load the page with it on, I get a FOUC (Flash Of Unstyled Content) for a brief moment, and then it renders properly.

If I wrap it in a <NoSSR> tag using react-no-ssr, I can bypass this visual bug.

You can see an example here:
https://imgur.com/a/b7EkSI1 

I figured this was due to SSR support?

My code with NoSSR:

`     <NoSSR
                          onSSR={
                            <Box flex='grow'>
                              <Text textAlign='center'>
                                {props.game.questions[0].question}
                              </Text>
                              <Text weight='bold' textAlign='center'>
                                {props.prediction[0]}
                              </Text>
                            </Box>
                          }
                        >
                          <Fade {...FadeProperties}>
                            {Object.keys(props.game.questions).map(
                              (key, idx) => {
                                return (
                                  <Box>
                                    <Text textAlign='center' color='light-1'>
                                      {props.game.questions[key].question}
                                    </Text>
                                    <Text
                                      weight='bold'
                                      color='light-1'
                                      textAlign='center'
                                    >
                                      {props.prediction[key]}
                                    </Text>
                                  </Box>
                                )
                              }
                            )}
                          </Fade>
                        </NoSSR>`

**Comment by rodrigofalco** [comment]
Is this working on latests nextjs (9.1.1)?
I get this error, even with the modifications in the next.config.js

> Build error occurred
{ /home/xxxxx/clients/projectname/projectfolder/node_modules/react-slideshow-image/lib/components/slideshow/general.css:1
.react-slideshow-container {
^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> ( /home/xxxxx/clients/projectname/projectfolder/node_modules/react-slideshow-image/lib/index.js:25:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) type: 'SyntaxError' }

**Comment by femioladeji** [comment]
Can you replace the content of your next.config.js file with this
```js
const withCSS = require("@zeit/next-css");
const resolve = require("resolve");
global.navigator = () => null;
module.exports = withCSS({
  webpack(config, options) {
    const { dir, isServer } = options;
    config.externals = [];
    if (isServer) {
      config.externals.push((context, request, callback) => {
        resolve(
          request,
          { basedir: dir, preserveSymlinks: true },
          (err, res) => {
            if (err) {
              return callback();
            }
            if (
              res.match(/node_modules[/\\].*\.css/) &&
              !res.match(/node_modules[/\\]webpack/) &&
              !res.match(/node_modules[/\\]react-slideshow-image/)
            ) {
              return callback(null, `commonjs ${request}`);
            }
            callback();
          }
        );
      });
    }
    return config;
  }
});
```
Here's a code sandbox sample

**Comment by rodrigofalco** [comment]
@femioladeji Wow you are responsive... thanks so much for this!.

It works now. I had to add some other libraries as well to the list of exclussions, like bootstrap, but the build process completes now.
Thanks again.
