### ISSUE TITLE
Bug: Tween not a constructor 

### ISSUE THREAD

**Issue by KevinKelbie** [femioladeji/react-slideshow#44]
I'm getting the following error message in the console.

        TypeError: a.Tween is not a constructor               fade.js:357

Weird thing is its only occurring on Azure when I deploy it and not when I'm running it locally.

My code:

        <Fade {...properties}>
              {
                props.images.map((image, i) => {
                  return <div className="each-slide">
                    <LazyLoad once>
                      <img src={image} alt=""/>
                    </LazyLoad>
                  </div>
                })
              }
            </Fade>

It was actually working on Azure for a while then suddenly stopped working so I thought maybe there was an update to the npm library. Does anyone have any ideas what could cause this?

**Comment by femioladeji** [comment]
@KevinKelbie that's strange. I'll look into this and get back to you later in the day

**Comment by KevinKelbie** [comment]
Let me know if you need anything from me to help with debugging.

**Comment by femioladeji** [comment]
@KevinKelbie what version of the package are you using? I'm trying to replicate the bug here but I couldn't

**Comment by KevinKelbie** [comment]
@femioladeji its happening with `^1.2.1` and `^1.2.2` 

Here is a live version of the site I am working on for a client. Its throws the error when you try to click on the arrows or wait for it to try and transition which it should do every few seconds: https://agileresource.co.uk/

**Comment by femioladeji** [comment]
hi @KevinKelbie after some investigations I discovered that the bug was introduced because of Tweenjs update to v18. I've released a new version, v1.3.0. That should fix the issue. Thanks for reporting this. Let me know if it works fine

**Comment by KevinKelbie** [comment]
Worked like a charm, thank you!
