### ISSUE TITLE
CSS conflicts with Bulma

### ISSUE THREAD

**Issue by refayathaque** [femioladeji/react-slideshow#48]
Thank you for creating such a nice node react package. Unfortunately, I think there are some CSS styles that are conflicting with my Bulma classes. How would I solve this issue?

**Comment by femioladeji** [comment]
I'll look into this and get back to you. Sorry about that @refayathaque

**Comment by femioladeji** [comment]
I tried to replicate it but can you share some snippet or perhaps share it with https://codesandbox.io/

**Comment by refayathaque** [comment]
Here is an image of my window without loading the fade component:
<img width="1845" alt="Screen Shot 2019-11-18 at 9 28 06 PM" src="https://user-images.githubusercontent.com/25051299/69111111-89901400-0a4a-11ea-90a8-4c8551cbbe15.png">
Here is the same window after loading the fade component, it is nested in between the Bulma tiles and the blurb:
<img width="1845" alt="Screen Shot 2019-11-18 at 9 28 41 PM" src="https://user-images.githubusercontent.com/25051299/69111149-a4fb1f00-0a4a-11ea-9df6-a3be01382a85.png">
I will also share the entire component code below:
`import React from 'react';
import AutoFader from 'components/AutoFader';

const Home = ({ selectTabFromChild }) => {
  const renderTiles = () => {
    return (
      <div class="tile is-ancestor">
        <div className="tile is-parent is-vertical">
          <article class="tile is-child has-background-dark box paddingThree">
            <p class="title is-3 is-italic has-text-white">Organizational</p>
          </article>
          <article class="tile is-child has-background-info box paddingThree">
            <p class="title is-3 is-italic has-text-white">Enterprise</p>
          </article>
        </div>
        <div className="tile is-parent is-vertical">
          <article class="tile is-child has-background-info box paddingThree">
            <p class="title is-3 is-italic has-text-white">Provider</p>
          </article>
          <article class="tile is-child has-background-dark box paddingThree">
            <p class="title is-3 is-italic has-text-white">Patient</p>
          </article>
        </div>
      </div>
    );
  };

  const renderButtons = () => {
    return (
      <div className="columns">
        <div id="marginRightOne" className="column">
          <button id="Get Involved" className="button is-warning is-fullwidth" onClick={event => selectTabFromChild(event.target.id)}>
            Subscribe
          </button>
        </div>
        <div id="marginLeftOne" className="column">
          <button className="button is-warning is-fullwidth">Contact Us</button>
        </div>
      </div>
    );
  };

  const renderBlurb = () => {
    return (
      <div className="has-background-success box">
        <div id="paddingSidesThree" className="">
          <div className="is-size-6 has-text-dark has-text-justified">
            Section 405(d) Task Group aims to <span className="has-text-weight-bold">raise awareness, provide vetted cybersecurity practices, and move organizations towards consistency in mitigating the current most pertinent cybersecurity threats</span> to the sector. It seeks to <span className="has-text-weight-bold">aid healthcare and public health organizations develop meaningful cybersecurity objectives and outcomes.</span>
          </div>
        </div>
      </div>
    );
  };

  const renderHeading = () => {
    return (
      <div id="paddingBottomOne">
        <h1 class="title is-3 has-text-dark">
          <span class="title is-3 has-text-danger">Absence</span> of Cybersecurity is a(n) ________ <span class="title is-3 has-text-danger">Risk</span>
        </h1>
      </div>
    );
  };

  return (
    <div className="container">
      <div className="columns has-text-centered is-vcentered">
        <div className="column">
          {renderHeading()}
          {renderTiles()}
          <AutoFader />
          {renderBlurb()}
          {renderButtons()}
        </div>
        <div className="column">
          <img src="http://d2mzatvmqghzct.cloudfront.net/home.jpg" width="619" height="670" />
        </div>
      </div>
    </div>
  );
};

export default Home;
`

**Comment by refayathaque** [comment]
[Untitled.txt](https://github.com/femioladeji/react-slideshow/files/3861654/Untitled.txt)

**Comment by femioladeji** [comment]
Hi @refayathaque I think if you try to add this to the `column` div it should work
I added the maxWidth to the `column` div. Let me know if that works
```
return (
    <div className="container">
      <div className="columns has-text-centered is-vcentered">
        <div className="column" style={{maxWidth: "50%"}}>
          {renderHeading()}
          {renderTiles()}
          <AutoFader />
          {renderBlurb()}
          {renderButtons()}
        </div>
        <div className="column">
          <img src="http://d2mzatvmqghzct.cloudfront.net/home.jpg" width="619" height="670" />
        </div>
      </div>
    </div>
  );
```

![Screenshot 2019-11-25 at 00 30 18](https://user-images.githubusercontent.com/17332992/69503533-c82a4080-0f1a-11ea-88a2-938b12f79b67.png)

**Comment by refayathaque** [comment]
Thank you so much, my friend! That worked! Check it out [here](https://405d.egt-labs.com)

**Comment by refayathaque** [comment]
Hi again @femioladeji ! I had a question regarding the responsiveness of the fix you provided above. If you try and access the website at [https://405d.egt-labs.com](https://405d.egt-labs.com) and play around with your browser size you will notice that the component gets not only disappears, but the layout of other elements are altered. I am having a hard time developing a permanent fix for this and would really appreciate your help.

**Comment by femioladeji** [comment]
I'll look into this and get back to you @refayathaque

**Comment by femioladeji** [comment]
Hi @refayathaque change this line
```
<div class="slide-container tile is-ancestor">
```
to 
```
<div class="slide-container">
```
that should work

**Comment by refayathaque** [comment]
Hi @femioladeji,

That did it! Thank you so much :)
