### ISSUE TITLE
Two slide effect are not worked parallel 

### ISSUE THREAD

**Issue by indu127pal** [femioladeji/react-slideshow#49]
If I'm using the two times side effect in a component than the first slide effect works but second is not working, it stops rotating the second component.

**Comment by femioladeji** [comment]
ok @indu127pal I'll get back to you about this

**Comment by femioladeji** [comment]
@indu127pal I've released a new version 1.3.2 to fix the bug.
Here is the PR #51 

Let me know if it works fine now.

**Comment by indu127pal** [comment]
Thanks, Oladeji Femi.
