### ISSUE TITLE
the indicators is gone if the list of slide is many

### ISSUE THREAD

**Issue by golestanirad** [femioladeji/react-slideshow#50]
i have around 100 slides and I get no indicators, I also noted for the smaller amount the indicators exist but it looks like little vertical lines than dots and if you click on one close to the end the slide is empty,

**Comment by femioladeji** [comment]
@golestanirad I'll look into this and get back to you soon

**Comment by femioladeji** [comment]
I'm guessing you want something like the image I attached right
![Screenshot 2019-12-17 at 02 34 05](https://user-images.githubusercontent.com/17332992/70957297-f3b1ce00-2075-11ea-9dfa-d777c971c4fd.png)

**Comment by femioladeji** [comment]
I've released v1.3.3 to fix this. Let me know if that works for you
