### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by theredwillow** [femioladeji/react-slideshow#53]
'@types/react-slideshow-image@latest' is not in the npm registry.

**Comment by femioladeji** [comment]
@theredwillow thanks for pointing that out. I'll look into it

**Comment by vince1393** [comment]
Having this issue as well. I'm using require() for now as a temporary fix, but it would be awesome if the package added type support

**Comment by femioladeji** [comment]
Thanks @vince1393 I just got back from vacation. I'll look into this ASAP to make it easier for typescript support

**Comment by jcosentino** [comment]
Is there a workaround for React with TypeScript?
I get this error:

> Could not find a declaration file for module 'react-slideshow-image'. '/Users/johncosentino/Github/portfolio-site/node_modules/react-slideshow-image/lib/index.js' implicitly has an 'any' type.
>   Try `npm install @types/react-slideshow-image` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-slideshow-image';`

**Comment by femioladeji** [comment]
Hi @jcosentino sorry for the late response. The typings have not been added to the `@types` repository.

What you can do for now is this

1. In your tsconfig.json file add this to the compiler options
```
"typeRoots": [
      "./types",
      "./node_modules/@types"
]```
2. Create a file in this directory `types/react-slideshow-image/index.d.ts`
3. Copy and paste this into it
```
declare module 'react-slideshow-image' {
    export class Zoom extends React.Component<ZoomProps & any, any> {
        goBack(): void;
        goNext(): void;
        goTo(index: number): void;
    }
    export class Fade extends React.Component<SlideshowProps & any, any> {
        goBack(): void;
        goNext(): void;
        goTo(index: number): void;
    }
    export class Slide extends React.Component<SlideshowProps & any, any> {
        goBack(): void;
        goNext(): void;
        goTo(index: number): void;
    }
    export interface SlideshowProps {
        duration?: number,
        transitionDuration?: number,
        defaultIndex?: number,
        indicators?: boolean,
        arrows?: boolean,
        autoplay?: boolean,
        infinite?: boolean,
        onChange?(oldIndex: number, newIndex: number): void,
        pauseOnHover?: boolean
    }
    export interface ZoomProps extends SlideshowProps {
        scale: number
    }
}

```
Let me know if that works for you

**Comment by jcosentino** [comment]
> 
> 
> Hi @jcosentino sorry for the late response. The typings have not been added to the `@types` repository.
> 
> What you can do for now is this
> 
>     1. In your tsconfig.json file add this to the compiler options
> 
> 
> ```json
> "typeRoots": [
>       "./types",
>       "./node_modules/@types"
> ]
> ```
> 
>     1. Create a file in this directory `types/react-slideshow-image/index.d.ts`
> 
>     2. Copy and paste this into it
> 
> 
> ```ts
> declare module 'react-slideshow-image' {
>     export class Zoom extends React.Component<ZoomProps & any, any> {
>         goBack(): void;
>         goNext(): void;
>         goTo(index: number): void;
>     }
>     export class Fade extends React.Component<SlideshowProps & any, any> {
>         goBack(): void;
>         goNext(): void;
>         goTo(index: number): void;
>     }
>     export class Slide extends React.Component<SlideshowProps & any, any> {
>         goBack(): void;
>         goNext(): void;
>         goTo(index: number): void;
>     }
>     export interface SlideshowProps {
>         duration?: number,
>         transitionDuration?: number,
>         defaultIndex?: number,
>         indicators?: boolean,
>         arrows?: boolean,
>         autoplay?: boolean,
>         infinite?: boolean,
>         onChange?(oldIndex: number, newIndex: number): void,
>         pauseOnHover?: boolean
>     }
>     export interface ZoomProps extends SlideshowProps {
>         scale: number
>     }
> }
> ```
> 
> Let me know if that works for you

Yes! That worked. Thank you so much, I appreciate it a lot.
