### ISSUE TITLE
Toggle autoplay programmatically

### ISSUE THREAD

**Issue by IpIvanov** [femioladeji/react-slideshow#55]
Is there an option to toggle the autoplay prop programmatically after the init of the slider?

I've tried with the state value but with no luck.

https://codesandbox.io/s/nostalgic-leavitt-r1vwr?fontsize=14&hidenavigation=1&theme=dark

**Comment by femioladeji** [comment]
@IpIvanov I'm investigating this now. I'll get back to you once I figure it out

**Comment by femioladeji** [comment]
PR raised to fix the issue #56

**Comment by femioladeji** [comment]
@IpIvanov thanks for pointing this out. I've released a new version `1.3.4` with the fix.

check it here https://codesandbox.io/s/quirky-leakey-xgxxh

**Comment by IpIvanov** [comment]
Thank you very much!
