### ISSUE TITLE
Conflicting with purge css.

### ISSUE THREAD

**Issue by zakirsajib** [femioladeji/react-slideshow#57]
warn chunk styles [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/lib??pos
tcss-2!./node_modules/react-slideshow-image/lib/components/slideshow/general.css
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader??ref--13-oneOf-1-1!./node_modules/postcss-loader/lib??pos

**Comment by femioladeji** [comment]
@zakirsajib I'll look into this and get back to you

**Comment by zakirsajib** [comment]
It happens when I build the site in gatsby. In `gatsby develop` command, all good, but when i command `gatsby build`, at last process, it breaks. Even netlify build fails.

The plugin `react-slideshow-image` and its css is the question. When I disable this plugin to use then everything looks fine. I used this plugin in twice on my gatsby site. in home page its still enable and no issue so far (build pass). But i used this plugin on another page and then it fails. I disabled it on that page and now it works. But i want to enable on both pages. So I am not sure whether its issue with purgecss or the slideshow plugin. 

on second page my code is like this.

`import { Slide } from 'react-slideshow-image'`

`let properties = {
	  autoplay: false,
	  duration: 5000,
	  transitionDuration: 500,
	  infinite: true,
	  indicators: true,
	  arrows: true,
	  onChange: (oldIndex, newIndex) => {
	    console.log(`slide transition from ${oldIndex} to ${newIndex}`);
	  }
	}`

and the exact code to display images is:

`<div className="slide-container">`
`<Slide {...properties}>`
`{singleCaseStudy.acf.case_study_gallery.map((each, index)=> (`
	`<img key={index} src={each.source_url} alt={singleCaseStudy.acf.client_name}/>`
`))}`
`</Slide>`
 `</div>`

I imported `slide` but used your `zoom` code from the example of your site. So its kinda mixed.
Do you think it could be the issue?

**Comment by femioladeji** [comment]
@zakirsajib sorry for my late response. Are you saying the bug only shows on the second page but it works out find on the homepage?

**Comment by zakirsajib** [comment]
Yes. It works without any issue on home page but it does not work if i used on other page.

**Comment by thokchomrs** [comment]
my style crase when I use

**Comment by femioladeji** [comment]
@thokchomrs you need to whitelist the `react-slideshow-container` class. Your purgecss config file should look similar to this
```js
module.exports = {
    content: ['build/index.html', 'build/static/js/*.js'],
    css: ['build/static/css/*.css'],
    output: ['build/static/css'],
    whitelist: [/react-slideshow-container/]
  }
```
