### ISSUE TITLE
Show me an example of goNext and goBack methods

### ISSUE THREAD

**Issue by zakirsajib** [femioladeji/react-slideshow#62]
Show me an example of goNext and goBack methods of Slide Effect or any Effect you have.

**Comment by femioladeji** [comment]
@zakirsajib here you go https://codesandbox.io/s/serene-lalande-yjmol

**Comment by femioladeji** [comment]
For more details about refs, [check this out](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs)

**Comment by umakantp** [comment]
Do we have an example of `React.useRef` instead of Legacy API ? Working with typescript would be best, somehow types are not proper which were shared already in another issue. Thanks
