### ISSUE TITLE
It is possible to swipe the slideshow and change autoplay props ? 

### ISSUE THREAD

**Issue by PironSteve** [femioladeji/react-slideshow#63]
I wonder if it is currently possible to swipe images on mobile phones?

By the way, I can't change the autoplay props. Either it's true or it's done, but I can't switch between the two. Is that even possible?

**Comment by femioladeji** [comment]
Yes, it's possible to change the `autoplay` prop. Check this sandbox https://codesandbox.io/s/quirky-leakey-xgxxh

Unfortunately, the swipe gesture functionality has not been implemented

**Comment by femioladeji** [comment]
@PironSteve click on the toggle autoplay button to see the effect

**Comment by PironSteve** [comment]
That's exactly what I did with the useState but I'm trying to do it when my div appears in scroll. Does it also work with the fade?

**Comment by femioladeji** [comment]
@PironSteve yes it works with fade too https://codesandbox.io/s/infallible-hertz-w3bsk

I think you should confirm that the state controlling the `autoplay` prop is actually changed

**Comment by PironSteve** [comment]
@femioladeji Thank you for your answer, 
I've debugged my condition and I fit in well, but it doesn't take the change of props on the scroll, it's weird.

**Comment by femioladeji** [comment]
Can you create something on codesandbox.io so that I can have a better view of whats happening

**Comment by PironSteve** [comment]
This is something like that: https://codesandbox.io/s/snowy-darkness-ihnls

**Comment by femioladeji** [comment]
@PironSteve is this what you're trying to do https://codesandbox.io/s/white-star-rp7it

**Comment by PironSteve** [comment]
That's exactly what i'm trying to do, thank you !

**Comment by femioladeji** [comment]
You're welcome. Glad I could help
