### ISSUE TITLE
Uncaught error in production: Cannot find module "./components/slideshow/general.css"

### ISSUE THREAD

**Issue by kalemi19** [femioladeji/react-slideshow#66]
Locally it works and loads perfectly, but when I deploy the app to production, the app doesn't load and in the console I see the following.

<img width="1440" alt="Screen Shot 2020-03-18 at 4 37 29 PM" src="https://user-images.githubusercontent.com/1066392/76978321-d6232780-6936-11ea-9483-25252627c85b.png">

Basically the deploy compiles the assets locally and copies them to the external server.

```
rm -rf public/assets public/packs
yarn install --production
NODE_ENV="production" RAILS_ENV="production" bundle exec rake assets:clean assets:precompile
```
I will try to locally run the app in production mode, but I was wondering if you had any clue.

Thanks

**Comment by femioladeji** [comment]
@kalemi19 the package has css files included in it. I'm guessing the css wasn't bundled together with the js files

**Comment by kalemi19** [comment]
Never mind. The assets:precompile was failing silently and when I ran it on it's own I got more helpful errors. Basically I had the `resolve-url-loader`, `sass-loader` and `style-loader` ONLY in `devDependencies`.

That's why it worked in development mode.

Once I moved them to dependencies it started working in production too.

Thank you for taking the time and good job :)
