### ISSUE TITLE
Implement Swipe

### ISSUE THREAD

**Issue by PironSteve** [femioladeji/react-slideshow#68]
Hi

I know the swipe is not integrated yet but I was wondering if it was possible to integrate it ourselves with some functions? 

I'm using the Fade effect, would it be possible to allow swipe with this transition effect?

Should I go on an EventListener?

Thanks in advance for the answers and advice

**Comment by femioladeji** [comment]
@PironSteve I guess this is what you want to do
https://codesandbox.io/s/agitated-tharp-jm586

You may want to adjust some parameters and remove anything you don't need

**Comment by femioladeji** [comment]
@PironSteve I hope ☝️ worked for you
