### ISSUE TITLE
Encapsulating div hiding Fade component causes image panel to incorrectly load 

### ISSUE THREAD

**Issue by jcosentino** [femioladeji/react-slideshow#69]
I am utilizing the Fade component inside of a div that initially hides it based on state.
The div, when set to any of the CSS properties, creates a distortion on initial set:
```
// option 1
.false {
  display: none;
}

// option 2
.false {
   position: absolute !important;
   top: -9999px !important;
   left: -9999px !important;
}

// option 3
.false { 
  position: absolute; 
  overflow: hidden; 
  clip: rect(0 0 0 0); 
  height: 1px; width: 1px; 
  margin: -1px; padding: 0; border: 0; 
}
```
When the Fade div is hidden by one of those methods, and then unhidden, whatever is inside of the div (images or text) will not be centered correctly. But, upon a zoom change or window size change, the div fixes itself.

Here is an Imgur album of the div before being displayed, initial opening, then after a rezoom:
https://imgur.com/a/GDu2sTr

I have created a sample project with a simple implementation with text (Stackblitz does not support images.
See: https://stackblitz.com/edit/react-8bjnge

**Comment by femioladeji** [comment]
@jcosentino try using `visibility: hidden` instead of `display: none`. I'll still look into fixing it when `display` css property is used

**Comment by femioladeji** [comment]
I think the best approach will be to use jsx to control when the slide is shown instead of using css. Setting display to none doesn't stop the slideshow from getting mounted.

I changed the `app.js` to this
```jsx
import React from 'react';
import { render } from 'react-dom';
import './style.css';
import { Fade } from 'react-slideshow-image';

function App() {
  const [isOpen, setOpen] = React.useState(false);
  const fadeProperties = {
    duration: 5000,
    transitionDuration: 500,
    infinite: true,
    indicators: true,
    pauseOnHover: true
  }

  function handleIsOpen(){
    return isOpen;
  }

    return (
    <div className='cont'>
      <button onClick={() => {setOpen(!isOpen)}}>CLICK</button>
      {
        isOpen && <div>
        <Fade {...fadeProperties}>
          <div className='each-fade'>
            <div className='image-panel-container'>
              <p>This is some example text</p>
            </div>
            <h2>label #1</h2>
          </div>

          <div className='each-fade'>
            <div className='image-panel-container'>
              <p>This is some example text</p>
            </div>
            <h2>label #2</h2>
          </div>

          <div className='each-fade'>
            <div className='image-panel-container'>
              <p>This is some example text</p>
            </div>
            <h2>label #3</h2>
          </div>
          
        </Fade>
       </div>
      }
     </div>
    );
}

render(<App />, document.getElementById('root'));
```
