### ISSUE TITLE
gatsbyjs integration

### ISSUE THREAD

**Issue by ilearnbydoing** [femioladeji/react-slideshow#71]
Hi,

Has anybody implemented with Gatsbyjs?

I am getting this issue in VS Code while importing the module
--
"Could not find a declaration file for module 'react-slideshow-image'. 'PATH/node_modules/react-slideshow-image/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-slideshow-image` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-slideshow-image';`ts(7016)"
--
Any idea?

thanks

**Comment by femioladeji** [comment]
@ilearnbydoing  Can you follow the instructions here #53
