### ISSUE TITLE
Avoid require() css

### ISSUE THREAD

**Issue by tfsjohan** [femioladeji/react-slideshow#72]
I'm trying to use this component in Next JS but it doesn't allow for CSS to be required. 

Would it be possible to avoid requiring the CSS files? Or a way to make it work with Next?

Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/react-slideshow-image/lib/components/slideshow/fade.js

**Comment by femioladeji** [comment]
Can you follow this https://github.com/femioladeji/react-slideshow/issues/43#issuecomment-600893858

I'll continue thinking of other solutions that won't require changing the next config file

**Comment by femioladeji** [comment]
@tfsjohan let me know if that ☝️  works for you

**Comment by tfsjohan** [comment]
Yes! Thank you. 

Quite hard to style it with Next. Would be nice if you could style arrows and indicators as props instead. And it's hard to make every hidden container height: 100%. It is solvable with global CSS, but that also kind of breaks some of the things I like with Next and its CSS model.

**Comment by femioladeji** [comment]
Yes there's a plan to make the arrows and indicators customizable. I'll work on it but I don't have an ETA for the feature yet

**Comment by tfsjohan** [comment]
Sounds good!

**Comment by femioladeji** [comment]
@tfsjohan I've released a new version that can allow you to use custom indicators. Check this section of the readme https://github.com/femioladeji/react-slideshow#customizing-indciators and you can check this sandbox to see how it works https://codesandbox.io/s/serene-lalande-yjmol?file=/src/App.js.

I'll work on allowing custom arrows also soon

**Comment by tfsjohan** [comment]
Just noticed that this component also breaks server side rendered hooks on Next, so it's quite unusable for me at the moment. 

Possible because of react and react-dom peerDependency versions.

**Comment by femioladeji** [comment]
@tfsjohan sorry about that. I'll take a more detailed look at how SSR apps can use the package easily. Thanks for the feedback

**Comment by tfsjohan** [comment]
Thanks! 

I liked the API otherwise. If it would have worked better with NextJS it would have been much of what I needed. 

I don’t know, but it might be as easy as bumping the react and react-dependencies to a version that supports hooks. 

// Johan

**Comment by femioladeji** [comment]
Can you please paste the error you're getting so that I can have a better insight into what's happening

**Comment by tfsjohan** [comment]
https://fb.me/react-invalid-hook-call <https://fb.me/react-invalid-hook-call>

Don’t have the exact message since I changed the code, but the error message links to this react article.

Regarding Next it only happens on the server, so it probably has more to do how Node resolves modules than Webpack.
