### ISSUE TITLE
slideshow wrong layout in gatsby 

### ISSUE THREAD

**Issue by FantasyVII** [femioladeji/react-slideshow#84]
Hi,

I am using the latest version of react-slideshow v2.0.1 and I am having an issue with the layout in gatsby. When I build the project in 'develop mode' it works perfectly fine. However, once I build in 'build mode' to release my site, everything falls apart.

The layout looks like this in build mode
![image](https://user-images.githubusercontent.com/36584990/86332225-468e5400-bc5b-11ea-83f9-c31e225b0708.png)

Here is my code

```
import React from 'react'
import { Slide } from 'react-slideshow-image';
import 'react-slideshow-image/dist/styles.css'

const Post = (props) => {

    const properties = {
        duration: 5000,
        transitionDuration: 500,
        infinite: true,
        indicators: true,
        arrows: true,
        pauseOnHover: true,
    }

    return (
        <div className="slide-container">
            <Slide {...properties}>
                {
                    props.slideImages.map((item) => {
                        return (
                            <div className="each-slide">
                                <img src={'.' + item} />
                            </div>
                        )
                    })
                }
            </Slide>
        </div>
    )
}

export default Post
```

Any idea why that is?

**Comment by femioladeji** [comment]
Hi, @FantasyVII I couldn't replicate this bug. I created a simple gatsby example [https://github.com/femioladeji/gatsby-slideshow-example]((https://github.com/femioladeji/gatsby-slideshow-example)) and it worked fine

**Comment by FantasyVII** [comment]
Hi @femioladeji 

thank you for the quick replay and help!'

I cloned your repo, installed gatsby, and ran the "gatsby build" command.
I opened the index.html from the public folder in chrome and I still got the same results
![image](https://user-images.githubusercontent.com/36584990/86339386-932a5d00-bc64-11ea-89d3-7f28058fc8c6.png)

If I type "gatsby develop" it works perfectly. Not in build mode though.
Also, you can see that gatsby astronaut image is extremely pixelated. That is not the case in develop mode.

I am not sure what I am doing wrong
I have node.js 12.18.2 installed using NVM

**Comment by femioladeji** [comment]
@FantasyVII Oooh you're not supposed to open the index.html, you have to run `yarn serve` after running `yarn build`. Check [the documentation](https://www.gatsbyjs.org/docs/quick-start/)

**Comment by FantasyVII** [comment]
> @FantasyVII Oooh you're not supposed to open the index.html, you have to run `yarn serve` after running `yarn build`. Check [the gatsby documentation](https://www.gatsbyjs.org/docs/quick-start/)

ooh wow, I feel really stupid.
Thank you so much for your help. I spent over 5 hours trying to debug this before I raised an issue here.

Apologies for wasting your time. Really appreciate the help!!! :D
