### ISSUE TITLE
Some slides not functioning since update 2.0.1

### ISSUE THREAD

**Issue by EliranGooner** [femioladeji/react-slideshow#86]
I recently updated ```react-slideshow-image``` to version 2.0.1 as the older versions didn't support SSR and it messed up my gatsby project.

Now the SSR is no longer an issue since the update but I noticed some slides not functioning correctly throughout my project now.

The repo is here: https://github.com/EliranGooner/zeitouni

I didn't send it to production yet but since the update on one page using the Fade option one image gets shown and the second is just a black image. Not sure what's going on there, here's the component: https://github.com/EliranGooner/zeitouni/blob/master/src/components/hero.js

The other incident with ```react-slideshow-image``` happens on another page where the arrows are not shown even though it specified and 2 of the 3 images appear way down on the page for some reason.
Here's the component: https://github.com/EliranGooner/zeitouni/blob/master/src/components/project-gallery.js

In this code I have a workaround for avoiding SSR issues but I tried it with ```react-slideshow-image``` directly and the same thing happens since the update.

Just to clarify, I didn't change anything in the code other than updating the component. Before that, everything was working if we don't count the SSR issues.

**Comment by femioladeji** [comment]
@EliranGooner did you import the styles? In version 2.0.1 you have to explicitly import the CSS file from the library?

**Comment by femioladeji** [comment]
In the `SSRFriendlyFade.js` file, you just need this.
`import "react-slideshow-image/dist/styles.css"` 
That should work.

**Comment by EliranGooner** [comment]
@femioladeji Thank you, forget about that one.
But apparently I still have issues completing the build without using the workaround mentioned above.
I'm getting the same error mentioned here: https://github.com/gatsbyjs/gatsby/issues/25298#issuecomment-649720609 without using the workaround.
Have any suggestions on how to fix this?

**Comment by femioladeji** [comment]
@EliranGooner you need to comment out the content of the `gatsby-node.js` file. It's not needed anymore

**Comment by femioladeji** [comment]
@EliranGooner I'm sure the issue has been resolved now. So I'll close this
