### ISSUE TITLE
"window" is not available during server side rendering.

### ISSUE THREAD

**Issue by AjayDhimanELS** [femioladeji/react-slideshow#93]
I have a simple React Class component where if user is logged in then they will see the content, but if not:

`(navigate('/app/login'))`

this navigate function of gatsby is causing issues for me.
while running npm build it says:
`window is not available during server side rendering`, and :

`var navigate = function navigate(to, options) 
{ window.___navigate(rewriteLinkPath(to, window.location.pathname), options); }; 
exports.navigate = navigate;`

(the error indicates at window)
Any possible solutions for me?

**Comment by femioladeji** [comment]
@AjayDhimanELS this bug is not related to `react-slideshow`. You should check out [this issue](https://github.com/gatsbyjs/gatsby/issues/12537) on gatsby repo

**Comment by marsidorowicz** [comment]
but u can use if (typeof window !== 'undefined') {} to work it around

**Comment by femioladeji** [comment]
@marsidorowicz I'll look into this and get back to you

**Comment by femioladeji** [comment]
@marsidorowicz I just looked into the code and discovered that I've actually refactored it to not use `window`. Are you experiencing this error again?
