### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by elainebyrne** [femioladeji/react-slideshow#94]
Installed and everything is working in localhost. However, when I put on production server after running "npm run build", the error comes

"**TypeError: Super expression must either be null or a function**"

```
import React from 'react';
import { Helmet } from 'react-helmet';
import { FormattedMessage } from 'react-intl';

import { Link } from 'react-router-dom';

import { Slide } from 'react-slideshow-image';
import 'react-slideshow-image/dist/styles.css'

export default function FeaturePage() {
  return (
    <div>
      <div className="slide-container">
        <Slide>
          <div className="each-slide">
            <div style={{'background': `blue`}}>
              <span>Slide 1</span>
            </div>
          </div>
          <div className="each-slide">
          <div style={{'background': `red`}}>
              <span>Slide 2</span>
            </div>
          </div>
          <div className="each-slide">
            <div style={{'background': `black`}}>
              <span>Slide 3</span>
            </div>
          </div>
        </Slide>
      </div>
    </div>
  );
}
```

Here's the screenshot of the error: https://ibb.co/k4RcTt8

**Comment by femioladeji** [comment]
@elainebyrne I can't replicate this. Are you sure you exported your custom component?

**Comment by femioladeji** [comment]
@elainebyrne can you let me know the version you're using and can you try and create a small sample project on [codesandbox.io](codesandbox.io). I've tried replicating the bug but I couldn't

**Comment by aningbo** [comment]
Okay. I'll see what can be done. I wonder if it's due to some conflict with another package. I'm using the following versions:

"react": "16.8.6",
"react-slideshow-image": "^3.0.2",

**Comment by femioladeji** [comment]
@aningbo have you been able to resolve this issue now?

**Comment by aningbo** [comment]
No. I ended up using "react-slick": "^0.27.1" instead. Thanks.
