### ISSUE TITLE
Question: Ease In Option? 

### ISSUE THREAD

**Issue by julia-bujalski** [femioladeji/react-slideshow#98]
Hi! I'm a UI/UX Designer using this slideshow for a personal project - I'm really enjoying it and am looking for a place to add in an "ease in" appearance to the slide (similar to the `transition-timing-function` tag in CSS). Do you know if that's possible with the current set up? 

Thanks!

**Comment by femioladeji** [comment]
@julia-bujalski currently it's not possible but I'll look into this. Thanks for bringing it up

**Comment by femioladeji** [comment]
@julia-bujalski I've released a new version `3.2.0` that has support for this. All you need to do is add a new prop `easing` and set it to one of `linear, ease, ease-in, ease-out, cubic, cubic-in, cubic-out`. ✌️

**Comment by julia-bujalski** [comment]
@femioladeji Thank you so much!! This is awesome 🚀
